name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    name: Build the kernel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup build kernel environment
      run: |
        sudo apt-get update
        sudo apt-get install libc6-dev clang flex bison libssl-dev bc python3 python2 zip unzip git lld llvm
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: Download Proton-clang
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/kdrag0n/proton-clang.git proton-clang --depth=1
        export PATH="$GITHUB_WORKSPACE/kernel_workspace/proton-clang/bin:$PATH"

    - name: Download kernel source
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/onurmercury/android_kernel_xiaomi_lahaina-docker.git --depth=1

    - name: Compiling Kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel_xiaomi_lahaina-docker
        bash ./build.sh
        filename=$(find . -name Quick* -printf '%f\n')
        echo $filename
        echo "FILENAME=$filename" >> $GITHUB_ENV

    - name: Uploading Kernel
      uses: actions/upload-artifact@v3
      with:
        name: QuicksilveR-Topaz_Docker
        path: ${{ github.workspace }}/kernel_workspace/android_kernel_xiaomi_lahaina-docker/${{ env.FILENAME }}
